/*
 * VoIP.ms SMS
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.kourlas.voipms_sms.utils

import net.kourlas.voipms_sms.sms.Message

/**
 * Detects and resolves message reactions ("tapbacks").
 *
 * VoIP.ms has no reaction concept: a reaction arrives as an ordinary inbound
 * SMS/MMS whose text is a localized sentence generated by the sender's app, and
 * it identifies its target only by quoting (a possibly truncated copy of) the
 * target message's text. The formats actually observed in the wild on this
 * account are:
 *
 *  - Android FR : a attribué la mention «<NBSP>Adore<NBSP>» à «<NBSP>texte<NBSP>»
 *  - Apple  EN  : Liked “texte”   (Loved/Disliked/Laughed at/Emphasized/Questioned)
 *  - Android EN : Reacted 😂 to “texte”
 *
 * [process] takes a conversation's messages in chronological order (oldest
 * first), pulls out the reaction messages, and maps each to the database ID of
 * the message it reacts to (matched by quoted text). Reactions whose target
 * cannot be found are left in the visible list so no information is lost.
 *
 * Quote matching tolerates the sender dropping spaces (especially around line
 * breaks) by falling back to a whitespace-insensitive comparison; validated
 * against this account's history with no false positives.
 */
object MessageReactions {

    // Minimum length for a whitespace-insensitive prefix match, to avoid
    // matching very short quotes to the wrong (longer) message.
    private const val MIN_NOSPACE_PREFIX = 10

    /** A reaction parsed from a message's text. */
    private data class ParsedReaction(
        val emoji: String,
        val quoteKey: String,
        val quoteNoSpace: String,
        val truncated: Boolean
    )

    /** Result of [process]: messages to show, plus reactions per target ID. */
    data class Result(
        val visibleMessages: List<Message>,
        val reactionsByMessageId: Map<Long, List<String>>
    )

    // Reaction word/verb (lowercased, accents included) -> display emoji.
    private val WORD_TO_EMOJI: Map<String, String> = mapOf(
        // ❤️ love
        "loved" to "❤️", "love" to "❤️",
        "adore" to "❤️", "adoré" to "❤️",
        "j'adore" to "❤️",
        // 👍 like
        "liked" to "👍", "like" to "👍",
        "aime" to "👍", "aimé" to "👍",
        "j'aime" to "👍",
        // 👎 dislike
        "disliked" to "👎", "dislike" to "👎",
        "pas aimé" to "👎", "je n'aime pas" to "👎",
        // 😂 laugh
        "laughed at" to "😂", "rires" to "😂",
        "rigolé" to "😂", "haha" to "😂",
        // ‼️ emphasize
        "emphasized" to "‼️", "souligné" to "‼️",
        // ❓ question
        "questioned" to "❓", "point d'interrogation" to "❓",
        "mis en doute" to "❓"
    )

    // « WORD » à « TARGET »
    private val ANDROID_FR = Regex(
        "a attribué la mention\\s*[«\"](.+?)[»\"]" +
            "\\s*à\\s*[«\"](.+)[»\"]\\s*$",
        RegexOption.IGNORE_CASE
    )

    // Reacted <emoji> to “TARGET”
    private val ANDROID_EN = Regex(
        "^Reacted\\s+(.+?)\\s+to\\s+[“\"](.+)[”\"]\\s*$",
        RegexOption.IGNORE_CASE
    )

    // VERB “TARGET”
    private val APPLE_EN = Regex(
        "^(Loved|Liked|Disliked|Laughed at|Emphasized|Questioned)" +
            "\\s+[“\"](.+)[”\"]\\s*$",
        RegexOption.IGNORE_CASE
    )

    private val WHITESPACE = Regex("\\s+")

    /**
     * Collapses reaction messages onto their targets.
     *
     * @param messagesOldestFirst Conversation messages, oldest first.
     */
    fun process(messagesOldestFirst: List<Message>): Result {
        if (messagesOldestFirst.isEmpty()) {
            return Result(messagesOldestFirst, emptyMap())
        }

        // Parse every message once, and precompute candidate keys.
        val parsed = messagesOldestFirst.map { parse(it.text) }
        val wsKeys = messagesOldestFirst.map { matchKey(it.text) }
        val nsKeys = messagesOldestFirst.map { noSpaceKey(it.text) }

        val reactions = LinkedHashMap<Long, MutableList<String>>()
        val hidden = HashSet<Long>()

        for (i in messagesOldestFirst.indices) {
            val reaction = parsed[i] ?: continue
            val targetIdx = findTarget(reaction, parsed, wsKeys, nsKeys, i)
            if (targetIdx >= 0) {
                val id = messagesOldestFirst[targetIdx].databaseId
                val list = reactions.getOrPut(id) { mutableListOf() }
                if (reaction.emoji !in list) {
                    list.add(reaction.emoji)
                }
                hidden.add(messagesOldestFirst[i].databaseId)
            }
        }

        val visible = if (hidden.isEmpty()) {
            messagesOldestFirst
        } else {
            messagesOldestFirst.filter { it.databaseId !in hidden }
        }
        return Result(visible, reactions)
    }

    /**
     * If [rawText] is a reaction, returns a short, human-readable one-line
     * preview (e.g. "👍 Merci !") suitable for the conversation list and
     * notifications, where there is no bubble to attach an emoji to. Returns
     * null if the text is not a recognized reaction.
     *
     * The reaction sentence already embeds (a copy of) the target's text, so
     * this needs no database lookup.
     */
    fun previewFor(rawText: String): String? {
        val text = normalize(rawText)
        if (text.isEmpty()) return null

        ANDROID_FR.find(text)?.let {
            return preview(wordToEmoji(it.groupValues[1]), it.groupValues[2])
        }
        ANDROID_EN.find(text)?.let {
            val emoji = it.groupValues[1].trim()
            if (emoji.isEmpty()) return null
            return preview(emoji, it.groupValues[2])
        }
        APPLE_EN.find(text)?.let {
            return preview(wordToEmoji(it.groupValues[1]), it.groupValues[2])
        }
        return null
    }

    private fun preview(emoji: String, target: String): String {
        val t = normalize(target).trim()
        return if (t.isEmpty()) emoji else "$emoji $t"
    }

    /**
     * Finds the index of the message that [reaction] (at index [i]) targets, by
     * scanning preceding non-reaction messages. Returns -1 if none matches.
     *
     * Pass 1 uses whitespace-normalized text; pass 2 falls back to dropping all
     * whitespace (the sender sometimes loses spaces around line breaks).
     */
    private fun findTarget(
        reaction: ParsedReaction,
        parsed: List<ParsedReaction?>,
        wsKeys: List<String>,
        nsKeys: List<String>,
        i: Int
    ): Int {
        if (reaction.quoteKey.isNotEmpty()) {
            var j = i - 1
            while (j >= 0) {
                if (parsed[j] == null) {
                    val ck = wsKeys[j]
                    if (ck.isNotEmpty() && (ck == reaction.quoteKey
                            || (reaction.truncated
                            && ck.startsWith(reaction.quoteKey)))
                    ) {
                        return j
                    }
                }
                j--
            }
        }

        if (reaction.quoteNoSpace.isNotEmpty()) {
            var j = i - 1
            while (j >= 0) {
                if (parsed[j] == null) {
                    val cn = nsKeys[j]
                    if (cn.isNotEmpty() && (cn == reaction.quoteNoSpace
                            || (cn.startsWith(reaction.quoteNoSpace)
                            && reaction.quoteNoSpace.length >= MIN_NOSPACE_PREFIX))
                    ) {
                        return j
                    }
                }
                j--
            }
        }

        return -1
    }

    private fun parse(rawText: String): ParsedReaction? {
        val text = normalize(rawText)
        if (text.isEmpty()) return null

        ANDROID_FR.find(text)?.let {
            return reactionFromWord(it.groupValues[1], it.groupValues[2])
        }
        ANDROID_EN.find(text)?.let {
            // The captured token is already an emoji; use it verbatim.
            val emoji = it.groupValues[1].trim()
            if (emoji.isEmpty()) return null
            val target = it.groupValues[2]
            return ParsedReaction(
                emoji, matchKey(target), noSpaceKey(target), isTruncated(target)
            )
        }
        APPLE_EN.find(text)?.let {
            return reactionFromWord(it.groupValues[1], it.groupValues[2])
        }
        return null
    }

    private fun reactionFromWord(word: String, target: String): ParsedReaction =
        ParsedReaction(
            wordToEmoji(word), matchKey(target), noSpaceKey(target),
            isTruncated(target)
        )

    private fun wordToEmoji(word: String): String {
        val key = normalize(word).lowercase()
        return WORD_TO_EMOJI[key] ?: word.trim()
    }

    /** Replaces exotic spaces with a normal space and trims. */
    private fun normalize(s: String): String =
        s.replace(' ', ' ')  // no-break space
            .replace(' ', ' ')  // narrow no-break space
            .replace(' ', ' ')  // thin space
            .trim()

    private fun isTruncated(target: String): Boolean {
        val t = normalize(target)
        return t.endsWith("…") || t.endsWith("...")
    }

    /** Normalized text with trailing truncation markers (… or ...) removed. */
    private fun stripTruncation(s: String): String {
        var t = normalize(s).trimEnd()
        while (true) {
            t = when {
                t.endsWith("…") -> t.dropLast(1).trimEnd()
                t.endsWith("...") -> t.dropLast(3).trimEnd()
                else -> return t
            }
        }
    }

    /** Comparison key: collapse whitespace runs, trim, lowercase. */
    private fun matchKey(s: String): String =
        stripTruncation(s).replace(WHITESPACE, " ").trim().lowercase()

    /** Whitespace-insensitive comparison key: all whitespace removed. */
    private fun noSpaceKey(s: String): String =
        stripTruncation(s).replace(WHITESPACE, "").lowercase()
}
